import { Product } from "../models/product";

export class ProductRepository {
  private products: Product[];

  constructor() {
    this.products = new Array<Product>(
      {
        id: 1,
        name: 'MacBook Pro',
        price: 2499,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mac-card-40-macbookpro-14-16-202410?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1731974949535',
        description: 'Premium laptop for professionals and creatives.',
        categoryId: 1,
        createdAt: new Date(),
        isConfirmed: true,
        details: '14-inch Retina display, M1 Pro chip, up to 64GB RAM, 512GB SSD.',
        stockAmount: 50,
        viewCount: 150
      },
      {
        id: 2,
        name: 'iMac',
        price: 1799,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mac-card-40-imac-202410?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1731974953703',
        description: 'All-in-one desktop with sleek design and powerful performance.',
        categoryId: 1,
        createdAt: new Date(),
        isConfirmed: true,
        details: '24-inch 4.5K Retina display, Apple M1 chip, 256GB SSD, 8GB RAM.',
        stockAmount: 45,
        viewCount: 220
      },
      {
        id: 3,
        name: 'Mac mini',
        price: 699,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mac-mini-digitalmat-gallery-3-202410?wid=728&hei=666&fmt=png-alpha&.v=1728341423793',
        description: 'Compact and powerful desktop for everyday tasks and more.',
        categoryId: 1,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Apple M2 chip, 8GB RAM, 256GB SSD, macOS Ventura.',
        stockAmount: 60,
        viewCount: 180
      },
      {
        id: 4,
        name: 'MacBook Air',
        price: 999,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mac-card-40-macbook-air-202410?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1731974970795',
        description: 'Ultra-light and portable laptop with long battery life.',
        categoryId: 1,
        createdAt: new Date(),
        isConfirmed: true,
        details: '13-inch Retina display, Apple M2 chip, 8GB RAM, 256GB SSD.',
        stockAmount: 55,
        viewCount: 160
      },
      {
        id: 5,
        name: 'iPad Pro',
        price: 1099,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/ipad-card-40-pro-202405?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1713920820026',
        description: 'The ultimate tablet for work, entertainment, and creativity.',
        categoryId: 2,
        createdAt: new Date(),
        isConfirmed: true,
        details: '12.9-inch Liquid Retina display, Apple M1 chip, 128GB storage.',
        stockAmount: 80,
        viewCount: 300
      },
      {
        id: 6,
        name: 'iPad Air',
        price: 599,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/ipad-card-40-air-202405?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1713920820139',
        description: 'Thin, light, and powerful tablet for everyday use.',
        categoryId: 2,
        createdAt: new Date(),
        isConfirmed: true,
        details: '10.9-inch Liquid Retina display, A14 Bionic chip, 64GB storage.',
        stockAmount: 65,
        viewCount: 200
      },
      {
        id: 7,
        name: 'iPad',
        price: 329,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/ipad-card-40-ipad-202410?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1727714411651',
        description: 'Affordable tablet with everything you need for casual use.',
        categoryId: 2,
        createdAt: new Date(),
        isConfirmed: true,
        details: '10.2-inch Retina display, A13 Bionic chip, 32GB storage.',
        stockAmount: 30,
        viewCount: 150
      },
      {
        id: 8,
        name: 'iPad Mini',
        price: 499,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/ipad-card-40-ipad-mini-202410?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1727281366305',
        description: 'Compact tablet with high-end performance in a small size.',
        categoryId: 2,
        createdAt: new Date(),
        isConfirmed: true,
        details: '8.3-inch Liquid Retina display, A15 Bionic chip, 64GB storage.',
        stockAmount: 40,
        viewCount: 220
      },
      {
        id: 9,
        name: 'iPhone 16 Pro',
        price: 1099,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-card-40-iphone16prohero-202409?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1725567335931',
        description: 'The latest iPhone with a powerful A16 chip and stunning display.',
        categoryId: 3,
        createdAt: new Date(),
        isConfirmed: true,
        details: '6.7-inch OLED display, A16 Bionic chip, 128GB storage.',
        stockAmount: 15,
        viewCount: 130
      },
      {
        id: 10,
        name: 'iPhone 16',
        price: 799,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-card-40-iphone16hero-202409?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1723234230295',
        description: 'Advanced smartphone with powerful features and sleek design.',
        categoryId: 3,
        createdAt: new Date(),
        isConfirmed: true,
        details: '6.1-inch OLED display, A15 Bionic chip, 64GB storage.',
        stockAmount: 20,
        viewCount: 100
      },
      {
        id: 11,
        name: 'iPhone 15',
        price: 899,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-card-40-iphone15hero-202309?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1693086290559',
        description: 'Next-gen iPhone with improved performance and camera features.',
        categoryId: 3,
        createdAt: new Date(),
        isConfirmed: true,
        details: '6.1-inch Super Retina XDR display, A15 Bionic chip, 128GB storage.',
        stockAmount: 50,
        viewCount: 180
      },
      {
        id: 12,
        name: 'iPhone 14',
        price: 749,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-card-40-iphone14-202209?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1693086290654',
        description: 'High-performance iPhone with enhanced camera system.',
        categoryId: 3,
        createdAt: new Date(),
        isConfirmed: true,
        details: '6.1-inch OLED display, A15 Bionic chip, 128GB storage.',
        stockAmount: 45,
        viewCount: 150
      },
      {
        id: 13,
        name: 'iPhone SE',
        price: 399,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-card-40-iphonese-202203?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1646415838921',
        description: 'Compact and affordable smartphone with great performance.',
        categoryId: 3,
        createdAt: new Date(),
        isConfirmed: true,
        details: '4.7-inch Retina display, A13 Bionic chip, 64GB storage.',
        stockAmount: 30,
        viewCount: 120
      },
      {
        id: 14,
        name: 'Apple Watch Series',
        price: 399,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-card-40-s10-202409?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1724168059157',
        description: 'Stylish smartwatch with fitness tracking and notifications.',
        categoryId: 4,
        createdAt: new Date(),
        isConfirmed: true,
        details: '40mm GPS model, Retina display, 18-hour battery life.',
        stockAmount: 25,
        viewCount: 80
      },
      {
        id: 15,
        name: 'Apple Watch Ultra',
        price: 799,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-card-40-ultra2-202409_GEO_TR?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1725113866545',
        description: 'Rugged smartwatch designed for extreme sports and adventures.',
        categoryId: 4,
        createdAt: new Date(),
        isConfirmed: true,
        details: '49mm GPS model, dual-frequency GPS, 36-hour battery life.',
        stockAmount: 50,
        viewCount: 110
      },
      {
        id: 16,
        name: 'Apple Watch SE',
        price: 279,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-card-40-se-202409?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=1724168056018',
        description: 'Affordable and feature-packed smartwatch with health tracking.',
        categoryId: 4,
        createdAt: new Date(),
        isConfirmed: true,
        details: '40mm GPS model, Retina display, 18-hour battery life.',
        stockAmount: 40,
        viewCount: 150
      },
      {
        id: 17,
        name: 'AirPods Pro 2',
        price: 249,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/airpods-pro-2-hero-select-202409?wid=890&hei=890&fmt=jpeg&qlt=90&.v=1724041669458',
        description: 'Premium noise-cancelling earbuds with improved sound quality.',
        categoryId: 5,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Active Noise Cancellation, Transparency mode, 6 hours battery life.',
        stockAmount: 60,
        viewCount: 130
      },
      {
        id: 18,
        name: 'AirPods 4',
        price: 199,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/airpods-4-anc-select-202409?wid=890&hei=890&fmt=jpeg&qlt=90&.v=1725502639798',
        description: 'Wireless earbuds with high-quality sound and long battery life.',
        categoryId: 5,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Spatial audio, 5 hours battery life, Siri support.',
        stockAmount: 30,
        viewCount: 120
      },
      {
        id: 19,
        name: 'AirPods Max',
        price: 549,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/airpods-max-select-202409-midnight?wid=890&hei=890&fmt=jpeg&qlt=90&.v=1724927451276',
        description: 'Over-ear headphones with exceptional sound and noise cancellation.',
        categoryId: 5,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Active Noise Cancellation, Spatial Audio, 20 hours battery life.',
        stockAmount: 50,
        viewCount: 200
      },
      {
        id: 20,
        name: 'Apple Pencil Pro',
        price: 699,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MX2D3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1713841707336',
        description: 'An essential tool for digital artists and designers, offering precision and comfort for all your creative tasks.',
        categoryId: 6,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Highly responsive, pressure-sensitive tip for drawing and writing. Compatible with iPads and tablets, ergonomic design for extended use.',
        stockAmount: 45,
        viewCount: 35
      },
      {
        id: 21,
        name: 'iPad Pro Magic Keyboard',
        price: 699,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MWR43TQ?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1713934215720',
        description: 'A premium keyboard for the iPad Pro, combining sleek design with a responsive typing experience.',
        categoryId: 6,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Features a full-size keyboard, backlit keys, and a trackpad, making it ideal for productivity on the go. Sturdy and easy to attach to the iPad Pro.',
        stockAmount: 32,
        viewCount: 27
      },
      {
        id: 22,
        name: 'Studio Display',
        price: 399,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/studio-display-gallery-1-202203?wid=640&hei=528&fmt=p-jpg&qlt=95&.v=1675709041796',
        description: '27-inch 5K Retina display with True Tone technology. Ideal for creative professionals needing precise color grading and high detail.',
        categoryId: 6,
        createdAt: new Date(),
        isConfirmed: true,
        details: '27-inch 5K Retina display with True Tone technology. Ideal for creative professionals needing precise color grading and high detail.',
        stockAmount: 60,
        viewCount: 19
      },
      {
        id: 23,
        name: 'Magic Keyboard',
        price: 1200,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MXK83TQ?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1729879576947',
        description: 'A beautifully designed keyboard offering a smooth typing experience and enhanced functionality for your devices.',
        categoryId: 6,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Low-profile keys, stable and responsive, providing a comfortable typing experience. Perfect for both casual and professional use.',
        stockAmount: 25,
        viewCount: 15
      },
      {
        id: 24,
        name: 'Magic Mouse',
        price: 450,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MXK63?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1730508287136',
        description: 'An elegant and ergonomic mouse that blends seamlessly with your workspace and offers smooth navigation.',
        categoryId: 6,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Multi-touch surface, compact design, and wireless connectivity make it perfect for everyday tasks. Long-lasting battery and comfortable to use.',
        stockAmount: 40,
        viewCount: 24
      },
      {
        id: 25,
        name: 'Magic Trackpad',
        price: 599,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MXKA3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1730508286011',
        description: 'A refined trackpad offering precise control and multi-touch gestures, ideal for creative work and general navigation.',
        categoryId: 6,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Large, smooth glass surface allows for fluid gestures. Ideal for those who prefer trackpads over traditional mice, with precision and ease of use.',
        stockAmount: 30,
        viewCount: 32
      },
      {
        id: 26,
        name: 'AirTag',
        price: 199,
        imgUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/airtag-single-select-202104_FV1?wid=890&hei=740&fmt=jpeg&qlt=90&.v=1617761670000',
        description: 'A small and powerful device that helps you track your valuables and never lose them again.',
        categoryId: 6,
        createdAt: new Date(),
        isConfirmed: true,
        details: 'Compact, lightweight design that fits easily onto keychains, bags, or other items. Use the Find My app to locate your things with ease.',
        stockAmount: 80,
        viewCount: 40
      }
    );
  }

  getProducts(): Product[] {
    return this.products;
  }
}
